### PR TITLE
Feat/create footer

### PR DESCRIPTION
**Pull request by guilhermefxs**
### What I did

Create a footer on client that hides itself on scroll

### How to test

1. Open the terminal and go to the folder of this project
2. In terminal type:

git checkout develop
git pull
git checkout feat/create-footer
cd client/
npm install
npm run start 

3. In your browser:
4.  Open localhost http://localhost:3000
5.  scroll the page down to the bottom and check if a footer shows up
6.  scroll up and check if the footer goes away
7.  change to mobile view by pressing F12 or ctrl+shift+I
8.  if necessary click on a phone icon on the top right of the page
9.  scroll to the bottom of the page and check if a footer shows up
10.  scroll up and check if the footer goes away
11.  scroll down again and check if a footer shows up
12.  tap in a arrow at the top of the footer and check if the footer goes away

### CODE REVIEW

**Review by Monterazo — CHANGES_REQUESTED** [review]
It doesn't work in all screen sizes

**Review by Monterazo — CHANGES_REQUESTED** [review]
Add box shadow

**Comment by guilhermefxs** [comment]
> It doesn't work in all screen sizes

now it does

**Comment by guilhermefxs** [comment]
> Add box shadow

now i did

**Review by Monterazo — APPROVED** [review]
It looks much better now!

**Review by viniciusscala — CHANGES_REQUESTED** [review]
- The footer breaks at 1025px of width
image

- In the mockup, the footer has a shadow

- In big resolutions, the footer keeps getting larger, and it shoud stop at 1920 of width

- Remove the PostList from the app

**Comment by guilhermefxs** [comment]
> * The footer breaks at 1025px of width
>   image
> * In the mockup, the footer has a shadow
> * In big resolutions, the footer keeps getting larger, and it shoud stop at 1920 of width
> * Remove the PostList from the app

Are you sure you are looking at the right version of it? It's working just perfectly here

**Review by viniciusscala — APPROVED** [review]
Everything is perfet!! Just remember to take off the posts before you merge

**Pull request merged**
