### PR TITLE
CODEOWNERS: add CODEOWNERS file with code owners info

### LINKED ISSUE #1: Add the CODEOWNERS file
## What to do

- [x] Create a branch comming out of the developer branch
- [x] Create a file called "CODEOWNERS" in the root of the project
- [x] Add this inside it
```
*   @viniciusscala @Monterazo @raissaheimann @guilhermefxs 
```
- [x] Open the pull request to merge your branch with the develop

### PR DESCRIPTION
**Pull request by guilhermefxs**
## What I did

- Create CODEOWNERS file
- Add information to it

## How to test

1. Open the terminal and go to the folder of this project

1. In terminal:
   1. git checkout codeOwners
   2. git pull
   3. open CODEOWNERS file

Resolves:** #1

### CODE REVIEW

**Review by Monterazo — APPROVED** [review]
It seems correct!

**Comment by guilhermefxs** [comment]
Add more details on how to test but great PR

**Review by raissaheimann — COMMENTED** [review]
Add more details on "how to test" and your commit name should show me type(name of the branch): comment, but everything else is perfect! :)

**Review by raissaheimann — APPROVED** [review]

**Review by viniciusscala — APPROVED** [review]
Be careful with all the patterns and remember to fill the github informations in the navbar

**Pull request merged**
